### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by ghecho** [objective-see/ReiKey#1]
The download [link](https://bitbucket.org/objective-see/deploy/downloads/ReiKey_1.0.0.zip) in the [website](https://objective-see.com/products/reikey.html) is broken. 

<img width="600" alt="screen shot 2018-12-30 at 11 25 36 am" src="https://user-images.githubusercontent.com/952873/50549629-ad295080-0c25-11e9-8a69-292fbdf7603b.png">

**Comment by kernel-sanders** [comment]
Correct link: https://bitbucket.org/objective-see/deploy/downloads/ReiKey_0.9.0.zip

**Comment by objective-see** [comment]
Just released version 1.0 - so the link is now points to the download. 
Direct Link: https://bitbucket.org/objective-see/deploy/downloads/ReiKey_1.0.0.zip
