### ISSUE TITLE
Configuration Window keeps respawning

### ISSUE THREAD

**Issue by Eagleo0** [objective-see/ReiKey#3]
Hey, 

I keep getting the configuration windows over and over again.
For example: I installed and configured it to launch at start and show no icon in the status menu bar.
When a new security event occurs it still prompts me with that same initial configuration window over and over.

<img width="699" alt="config" src="https://user-images.githubusercontent.com/9079111/50574394-50c25e80-0de8-11e9-8cf4-03d3542856de.png">

Thanks for writing awesome macOS Security Software

Best regards
Andy S.

**Comment by objective-see** [comment]
Thanks for reporting! 
Just committed a fix to address this :)
