### ISSUE TITLE
Unable to quit Reikey 

### ISSUE THREAD

**Issue by Mortennn** [objective-see/ReiKey#4]
The "Quit"-option in the menu bar does not quit the app. It only closes the preferences window.
The only way I was able to close the app was from the Activity Monitor.

Thanks for developing this app and thank you for your work!

**Comment by objective-see** [comment]
Thanks for reporting! 
The scan and preference windows, are actually part of the main app (while the status icon belong to a login item, that is automatically started when the user logs in) ... this is why the 'Quit' didn't close the status bar. 

I added a `Quit` option to the status bar - which will now fully quit the listener/alerting login item

![image](https://user-images.githubusercontent.com/11327812/50669159-a5d8ae80-0f67-11e9-8aa1-dc8e1df1adba.png)

**Comment by Mortennn** [comment]
Thank you for the fixes!
