### ISSUE TITLE
Reikey keeps detecting "ViewBridgeAuxiliary"

### ISSUE THREAD

**Issue by Mortennn** [objective-see/ReiKey#5]
The only other app I can think of which might trigger Reikey is Karabiner Elements. 

<img width="1212" alt="scan" src="https://user-images.githubusercontent.com/34214574/50608946-6e69f380-0ece-11e9-9183-a4c6ff31849a.png">
<img width="394" alt="notifications" src="https://user-images.githubusercontent.com/34214574/50608947-6e69f380-0ece-11e9-989d-affefc253ef9.png">

**Comment by objective-see** [comment]
Thanks for reporting! 
Version 1.0 (just released) will ignore subsequent alerts from the same process....however, if new instances `ViewBridgeAuxiliary` are being spawned and register an event tap, will still be detected.

Still thinking on ways to address this. Maybe whitelist `ViewBridgeAuxiliary`

**Comment by JayBrown** [comment]
Yup, same on v1.0.1

![snap](https://i.imgur.com/nbsHydr.jpg)

**Comment by JayBrown** [comment]
Still in v1.0.2.

You could probably whitelist all Apple-signed processes (`Software Signing`) with `anchor apple`.

![snap](https://i.imgur.com/Oe8ukFW.jpg)

**Comment by objective-see** [comment]
Added preference to ignore Apple signed processes:

![image](https://user-images.githubusercontent.com/11327812/50732804-26dda480-1126-11e9-9439-b578d4313091.png)

**Comment by MaraLuna** [comment]
@objective-see  --
So can you tell us what the ViewBridgeAuxillary is?  What's it's purpose and what info does it log and send to where?
