### ISSUE TITLE
ReiKey Helper: crash on Mojave 10.14.2

### ISSUE THREAD

**Issue by JayBrown** [objective-see/ReiKey#7]
See crash report below. Happened when accessing the hidden Bartender menu bar to click on the MailButler icon.
[ReiKey Helper_2019-01-04-160118.txt](https://github.com/objective-see/ReiKey/files/2727518/ReiKey.Helper_2019-01-04-160118.txt)

**Comment by objective-see** [comment]
Thanks for the report! 
This should be fixed (https://github.com/objective-see/ReiKey/commit/c0124824d88151d0b8479217efe7ea716ddf7443) 

...can you download and test the latest version at your convenience? (https://objective-see.com/products/reikey.html) Thanks!! 🙏
